apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Values.analysis.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  metrics:
    - name: {{ .Values.analysis.metricName }}
      interval: {{ .Values.analysis.interval }}
      count: {{ .Values.analysis.count }}
      successCondition: result[0] > {{ .Values.analysis.minRequestRate }}
      failureLimit: {{ .Values.analysis.failureLimit }}
      provider:
        prometheus:
          address: {{ .Values.analysis.prometheusAddress }}
          query: |
            sum(prediction_api_requests_total) or vector(0)
