apiVersion: v1
kind: Service
metadata:
  name: {{ include "prediction-api.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "prediction-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "prediction-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
