apiVersion: v1
kind: Service
metadata:
  name: prediction-api
  namespace: prediction-api
  labels:
    app.kubernetes.io/name: prediction-api
    app.kubernetes.io/part-of: mlops-devsecops-demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prediction-api
  ports:
    - name: http
      port: 80
      targetPort: http
